#!/usr/bin/env node
/**
 * node --test tools/fleet-inline-template.test.js
 *
 * The Workflow runtime cannot `require()`, so the fleet script needs its pure helpers in its own
 * text. They used to be hand-copied there behind a marker pair each - the tests pinned the copies
 * against `tools/ticket-fleet-branch.js`, so drift was caught rather than shipped, but every new
 * behavior added another twin an editor had to remember (issue 440). The block is now GENERATED by
 * `tools/build-fleet-inline.js`, and these tests are the tripwire: a fix to the module that is not
 * regenerated fails here rather than shipping a fleet script running the older logic.
 */
'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { test } = require('node:test');

const { renderScript, SOURCE, TARGET, TARGET_START, TARGET_END } = require('./build-fleet-inline.js');
const module_ = require('./ticket-fleet-branch.js');

const REPO_ROOT = path.resolve(__dirname, '..');
const PACKAGED = path.join(REPO_ROOT, 'marketplace', 'aac-skills', 'skills', 'ticket-fleet',
                           'ticket-fleet.js');

/** The text between the fleet script's FLEET-GENERATED markers. */
function generatedBlock(file) {
  const text = fs.readFileSync(file, 'utf8');
  const s = text.indexOf(TARGET_START);
  const e = text.indexOf(TARGET_END);
  assert.ok(s >= 0 && e > s, `${file} is missing its FLEET-GENERATED markers`);
  return text.slice(s + TARGET_START.length, e);
}

test('the fleet script holds the generated copy of tools/ticket-fleet-branch.js, byte for byte', () => {
  const script = fs.readFileSync(TARGET, 'utf8');
  assert.strictEqual(
    script,
    renderScript(script, fs.readFileSync(SOURCE, 'utf8')),
    'the fleet script\'s generated block is stale — run: node tools/build-fleet-inline.js'
  );
  assert.strictEqual(
    generatedBlock(PACKAGED),
    generatedBlock(TARGET),
    'the packaged fleet script carries an older generated block — rebuild marketplace/ per CLAUDE.md'
  );
});

test('the generated block runs the module\'s helpers, not a copy that has drifted', () => {
  // eslint-disable-next-line no-new-func
  const inlined = new Function(`${generatedBlock(TARGET)}
    return { pickInstrument, pickVerifierAgent, resolveVerifierAgent, confineToCandidates,
             applyBlockerStates, stableJson, stableText, stableList, priorFindingsBlock };`)();

  assert.strictEqual(inlined.pickInstrument(null, undefined, undefined),
    module_.pickInstrument(null, undefined, undefined));
  assert.strictEqual(inlined.pickInstrument({ CLAUDE_CODE_REMOTE_SESSION_ID: 'x' }, true, 'auto'),
    module_.pickInstrument({ CLAUDE_CODE_REMOTE_SESSION_ID: 'x' }, true, 'auto'));
  assert.strictEqual(inlined.pickVerifierAgent(false, true), module_.pickVerifierAgent(false, true));
  assert.strictEqual(inlined.resolveVerifierAgent('gh', undefined, { remote: true, verifierAgentFile: true }),
    module_.resolveVerifierAgent('gh', undefined, { remote: true, verifierAgentFile: true }));
  assert.deepStrictEqual(inlined.confineToCandidates([{ number: 11 }, { number: 12 }], [12]),
    module_.confineToCandidates([{ number: 11 }, { number: 12 }], [12]));

  const tickets = [{ number: 30, blockedBy: [199, 206] }];
  const blockers = [{ number: 199, state: 'closed' }, { number: 206, state: 'open' }];
  assert.deepStrictEqual(inlined.applyBlockerStates(tickets, blockers),
    module_.applyBlockerStates(tickets, blockers));

  const verdict = { failures: ['a\r\nb ', null, 42] };
  assert.strictEqual(inlined.priorFindingsBlock(verdict, 'fix it'),
    module_.priorFindingsBlock(verdict, 'fix it'));
  assert.strictEqual(inlined.stableJson({ b: 1, a: undefined }), module_.stableJson({ b: 1, a: undefined }));
  assert.strictEqual(inlined.stableText('a\r\nb  '), module_.stableText('a\r\nb  '));
  assert.deepStrictEqual(inlined.stableList(['x', '', null]), module_.stableList(['x', '', null]));
});
